<a href="https://colab.research.google.com/github/PeruthAshaba/Ashaba/blob/main/Ashaba1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.zeros(3)
a


array([0., 0., 0.])

In [5]:
type(a)    #knowing the type of the array

numpy.ndarray

In [6]:
type(a[0])  #float is the same as decimal point

numpy.float64

In [7]:
a.shape   #getting  shape

(3,)

In [10]:
a.shape = (3,1)
a

array([[0.],
       [0.],
       [0.]])

In [14]:
z = np.zeros(4)
z

array([0., 0., 0., 0.])

In [15]:
z.shape = (2, 2)
z

array([[0., 0.],
       [0., 0.]])

In [16]:
a = np.ones(3)
a

array([1., 1., 1.])

In [22]:
a = np.empty(6)
a

array([3.60105635e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [24]:
a = np.identity(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
a = np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
z = np.array([1, 2])
print(z)

[1 2]


In [29]:
type(z)

numpy.ndarray

In [32]:
x = np.array([1, 2], dtype = float)
print(x)

[1. 2.]


In [33]:
y = np.array([[1, 2],[3, 4]])   #a 2D array is a list of lists
print(y)

[[1 2]
 [3 4]]


**Array indexing**

In [34]:
z = np.linspace(1, 2, 3)
z

array([1. , 1.5, 2. ])

In [36]:
z[2]


2.0

In [37]:
z[0:2]

array([1. , 1.5])

In [38]:
z[-1]

2.0

**Array** **Methods**

In [46]:
x = np.array([4, 3, 2, 1])
x.sort()
x

array([1, 2, 3, 4])

In [48]:
x.sum()


10

In [49]:
x.mean()

2.5

In [50]:
x.max()

4

In [51]:
x.min()

1

In [52]:
x.argmax()

3

In [53]:
x.cumsum()

array([ 1,  3,  6, 10])

In [54]:
x.cumprod()

array([ 1,  2,  6, 24])

In [55]:
x.var()

1.25

In [56]:
x.std()

1.118033988749895

Arithmatic products, include +, *, /, -

In [57]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a+b

array([ 6,  8, 10, 12])

In [58]:
a*b

array([ 5, 12, 21, 32])

In [59]:
a + 10   #scalar addition

array([11, 12, 13, 14])

In [60]:
a*10

array([10, 20, 30, 40])

In [61]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A+B

array([[2., 2.],
       [2., 2.]])

In [62]:
A*B

array([[1., 1.],
       [1., 1.]])

In [63]:
A + 10

array([[11., 11.],
       [11., 11.]])

In [64]:
A * 10

array([[10., 10.],
       [10., 10.]])

In [65]:
A @ B

array([[2., 2.],
       [2., 2.]])

Comparisons

In [68]:
z = np.array([2, 3])
x = np.array([2, 3])
z==x 

array([ True,  True])

In [69]:
z!=x

array([False, False])

In [70]:
z>=x

array([ True,  True])

In [71]:
z<=x

array([ True,  True])